### ISSUE TITLE
コード等のライセンスについて

### ISSUE THREAD

**Issue by esperecyan** [xelloss120/CharWebCam#2]
こちらのリポジトリのファイルのうち、ユニティちゃん、RealSenseSDK以外の部分について、ライセンスはどうなっていますか？

**Comment by xelloss120** [comment]
MITにしました。
https://github.com/xelloss120/CharWebCam/blob/master/LICENSE
README.md更新しました。
https://github.com/xelloss120/CharWebCam/blob/master/README.md

**Comment by esperecyan** [comment]
MITですね。ライセンス設定していただきありがとうございます。
